In [3]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [4]:
from sklearn import datasets

In [8]:
iris=datasets.load_iris()

In [9]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
x=iris.data[:,2:]
print(x)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [12]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
y=iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from sklearn.model_selection  import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [22]:
x_train_scaled

array([[-0.09951105, -0.32339776],
       [ 0.71770262,  0.35303182],
       [ 0.95119225,  0.75888956],
       [ 0.30909579,  0.2177459 ],
       [ 1.30142668,  1.70589097],
       [ 0.19235097,  0.08245999],
       [ 1.59328871,  1.16474731],
       [ 0.36746819,  0.35303182],
       [-1.44207638, -1.40568508],
       [ 1.65166111,  1.0294614 ],
       [ 0.13397857, -0.32339776],
       [-1.44207638, -1.40568508],
       [-1.50044878, -1.27039917],
       [-1.15021435, -1.13511325],
       [-0.21625586, -0.32339776],
       [ 0.60095781,  0.75888956],
       [-1.15021435, -1.40568508],
       [-1.32533157, -1.40568508],
       [-1.26695916, -0.99982734],
       [ 0.19235097,  0.08245999],
       [-1.38370397, -1.40568508],
       [ 0.19235097, -0.05282593],
       [ 1.65166111,  1.30003323],
       [-1.44207638, -1.40568508],
       [ 0.25072338,  0.08245999],
       [ 0.65933022,  1.0294614 ],
       [-1.44207638, -1.40568508],
       [ 0.54258541,  0.75888956],
       [ 0.71770262,

In [23]:
x_test_scaled

array([[ 0.484213  , -0.05282593],
       [-1.26695916, -1.27039917],
       [ 1.76840592,  1.43531914],
       [ 0.36746819,  0.35303182],
       [ 0.54258541,  0.2177459 ],
       [-1.38370397, -1.13511325],
       [-0.15788346,  0.08245999],
       [ 0.71770262,  1.43531914],
       [ 0.36746819,  0.35303182],
       [ 0.01723376, -0.05282593],
       [ 0.71770262,  1.0294614 ],
       [-1.44207638, -1.540971  ],
       [-1.50044878, -1.40568508],
       [-1.38370397, -1.540971  ],
       [-1.38370397, -1.27039917],
       [ 0.484213  ,  0.48831773],
       [ 1.12630946,  1.30003323],
       [ 0.01723376, -0.18811184],
       [ 0.36746819,  0.08245999],
       [ 1.00956465,  1.30003323],
       [-1.32533157, -1.40568508],
       [ 0.60095781,  0.75888956],
       [-1.32533157, -1.13511325],
       [ 1.00956465,  1.16474731],
       [ 1.47654389,  1.0294614 ],
       [ 0.77607503,  1.43531914],
       [ 1.12630946,  0.75888956],
       [ 1.18468187,  1.43531914],
       [-1.44207638,

In [26]:
from sklearn.svm import SVC

In [27]:
#HARD MARGIN
svm_hard_margin=SVC(kernel="linear",C=0.1e9)
svm_hard_margin.fit(x_train_scaled,y_train)

SVC(C=100000000.0, kernel='linear')

In [31]:
y_pred_hard_margin=svm_hard_margin.predict(x_test_scaled)
print(y_pred_hard_margin)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [32]:
from sklearn.metrics import accuracy_score
accuracy_hard_margin=accuracy_score(y_test,y_pred_hard_margin)

In [33]:
print("Accuracy (hard margin svm):",accuracy_hard_margin)

Accuracy (hard margin svm): 0.9777777777777777


In [34]:
#SOFT MARGIN
svm_soft_margin=SVC(kernel="linear",C=0.1)
svm_soft_margin.fit(x_train_scaled,y_train)

SVC(C=0.1, kernel='linear')

In [35]:
y_pred_soft_margin=svm_hard_margin.predict(x_test_scaled)
print(y_pred_soft_margin)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [37]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [36]:
accuracy_soft_margin=accuracy_score(y_test,y_pred_soft_margin)
print("Accuracy (SOFT margin svm):",accuracy_soft_margin)

Accuracy (SOFT margin svm): 0.9777777777777777
